### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by nickserv** [k23Burke/react-webaudio-examples#1]
```
./src/simplePlay.js
Module not found: Can't resolve './assets/sources' in '/Users/nick/Repos/react-webaudio-examples/src'
```

It seems like something in assets isn't checked into the GitHub repo.

**Comment by k23Burke** [comment]
@nickmccurdy thanks for catching this before I shared with everyone! I had to .gitignore the sources I used due to copyright infringement policies if up uploaded/distributed them!

**Comment by oftenfrequent** [comment]
@nickmccurdy thanks for catching this before I shared with everyone! I had to .gitignore the sources I used due to copyright infringement policies if up uploaded/distributed them!

I just pushed a new commit which references some freely distributed audio files hosted at [http://freemusicarchive.org/](http://freemusicarchive.org/) and it's now on master.

**Comment by nickserv** [comment]
Thanks for the quick response! It seems like `assets` still only contains `BatteryBenson.wav` and `source.example` is still in the `.gitignore`, did you forget to commit it? Note that `git add` does not include ignored files unless you use `--force`.

**Comment by oftenfrequent** [comment]
Hah yeah it's `sources.example` not `source.example` as I had in my `.gitignore` file 🤦‍♂️ 

Also gave me a chance to include a README - so we'll consider that a bonus for now.

See you Saturday?

**Comment by nickserv** [comment]
Cool thanks, the examples are working! And I probably will. 😄
